name: "Copilot Setup Steps"

# Automatically run when the file changes to allow for easy validation,
# and allow manual testing through the repository's "Actions" tab.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Lowest permissions needed; Copilot gets its own token for its operations.
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/workflows/install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache-version: copilot
          needs: build, check, website
          extra-packages: any::rcmdcheck any::roxygen2 any::pkgdown local::.

      - name: Install air
        uses: posit-dev/setup-air@v1
